"use client";

import { useState } from "react";
import { BadgeIndianRupee, Building2, Check, ChevronRight, CircleCheckBig, FileText, FolderOpen, GitCompareArrows, LayoutDashboard, ListChecks, TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";
import { Dot, Eyebrow, Panel, Section, Tag } from "./primitives";

const MODULES = [
  ["overview", "Overview", LayoutDashboard, "A partner view across the practice."],
  ["clients", "Clients", Building2, "One client record becomes the source for everything that follows."],
  ["work", "Work", ListChecks, "Recurring compliance becomes assigned work automatically."],
  ["documents", "Documents", FolderOpen, "Requests become tracked work instead of scattered messages."],
  ["billing", "Billing", BadgeIndianRupee, "Completed work connects naturally to billing."],
  ["reconciliation", "Reconciliation", GitCompareArrows, "Exceptions become reviewable tasks."],
  ["compliance", "Compliance", FileText, "Deadlines stay visible before they become overdue."],
] as const;

type Module = (typeof MODULES)[number][0];
type ClientTab = "Master" | "Tasks" | "Invoices" | "Documents" | "Activity";
const card = "rounded-xl border border-mkt-border bg-mkt-surface-2 p-3.5";

function AppWindow({ children }: { children: React.ReactNode }) {
  return <Panel className="min-h-[500px] overflow-hidden bg-mkt-surface shadow-[var(--mkt-shadow-elegant)] md:min-h-[560px]"><div className="flex h-12 items-center justify-between border-b border-mkt-border px-4"><span className="font-mkt-display text-[15px] font-semibold tracking-[-.03em] text-mkt-fg">Artha.</span><div className="flex items-center gap-2.5"><span className="rounded-md border border-mkt-border bg-mkt-surface-2 px-2 py-1 text-[10px] text-mkt-fg-muted">All Clients</span><span className="grid size-6 place-items-center rounded-full bg-[var(--mkt-wash-hi)] text-[10px] font-semibold text-mkt-primary">P</span></div></div>{children}</Panel>;
}
function Metric({ label, value, sub, tone = "accent" }: { label: string; value: string; sub: string; tone?: "accent" | "high" | "medium" }) { return <div className={card}><div className="mb-2 flex items-center gap-1.5"><Dot tone={tone === "accent" ? "accent" : tone}/><span className="text-[9px] tracking-[.08em] text-mkt-fg-muted uppercase">{label}</span></div><p className="mkt-num font-mkt-display text-[21px] leading-none font-semibold text-mkt-fg">{value}</p><p className="mt-1.5 text-[10px] text-mkt-fg-muted">{sub}</p></div>; }
function Rows({ rows }: { rows: string[][] }) { return <div className="overflow-hidden rounded-xl border border-mkt-border">{rows.map(([a,b,c]) => <div key={a} className="flex items-center gap-3 border-b border-mkt-border bg-mkt-surface-2 px-3 py-3 last:border-0"><span className="min-w-0 flex-1 text-[12px] text-mkt-fg">{a}</span><span className="hidden text-[10.5px] text-mkt-fg-muted sm:block">{b}</span><span className="text-right text-[10.5px] text-mkt-primary">{c}</span></div>)}</div>; }

function Overview() { return <AppWindow><div className="p-4 md:p-5"><div className="mb-5 flex items-end justify-between gap-3"><div><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">Good morning, Priya</p><p className="mt-1 text-[11px] text-mkt-fg-muted">Your practice at a glance · Monday, 17 August</p></div><Tag tone="accent">Partner view</Tag></div><div className="grid grid-cols-2 gap-2.5 lg:grid-cols-3"><Metric label="Overdue work" value="7" sub="2 added today" tone="high"/><Metric label="Due soon" value="9" sub="Next 7 days" tone="medium"/><Metric label="Reconciliation" value="4" sub="Exceptions to review"/><Metric label="Outstanding" value="₹4.2L" sub="16 clients"/><Metric label="Revenue (MTD)" value="₹1.21Cr" sub="This month"/><Metric label="Team capacity" value="74%" sub="4 people available"/></div><div className="mt-5 grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className={card}><p className="mb-3 text-[10px] tracking-[.1em] text-mkt-fg-muted uppercase">Needs attention</p>{[["GST reconciliation failed","Kavya Exports","High risk"],["GSTR-3B due","Meridian Textiles","3 days"],["DSC expiring","Sri Balaji Traders","12 days"]].map(([title,client,state],i)=><div key={title} className="flex items-center gap-3 border-t border-mkt-border py-3 first:border-0 first:pt-0"><Dot tone={i===0?"high":"medium"}/><span className="min-w-0 flex-1"><span className="block text-[12px] text-mkt-fg">{title}</span><span className="block text-[10px] text-mkt-fg-muted">{client}</span></span><Tag tone={i===0?"high":"medium"}>{state}</Tag></div>)}</div><Workload/></div></div></AppWindow>; }
function Workload(){return <div className={card}><p className="mb-3 text-[10px] tracking-[.1em] text-mkt-fg-muted uppercase">Team workload</p>{[["Ravi Kumar",92],["Anil Menon",64],["Priya Shetty",38],["Neha Sharma",74]].map(([name,value])=><div key={name as string} className="mb-3 last:mb-0"><div className="mb-1 flex justify-between text-[10.5px]"><span className="text-mkt-fg">{name}</span><span className="mkt-num text-mkt-fg-muted">{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-mkt-surface-3"><span className="block h-full rounded-full bg-mkt-primary" style={{width:`${value}%`}}/></div></div>)}</div>}

function Clients(){const [tab,setTab]=useState<ClientTab>("Master");const tabs:ClientTab[]=["Master","Tasks","Invoices","Documents","Activity"];const content:Record<ClientTab,React.ReactNode>={Master:<div className="grid gap-3 sm:grid-cols-2">{[["Entity type","Partnership firm"],["GSTIN","37AABFV2281R1ZV"],["PAN","AABFV2281R"],["Primary contact","V. Srinivasulu"],["Services","GST · TDS · Audit"],["Filing cycle","Monthly"]].map(([k,v])=><div key={k} className={card}><p className="text-[9px] tracking-[.08em] text-mkt-fg-muted uppercase">{k}</p><p className="mt-2 text-[12px] text-mkt-fg">{v}</p></div>)}</div>,Tasks:<Rows rows={[["GSTR-3B · July filing","Priya Shetty","Due in 3 days"],["Audit working papers","Ravi Kumar","In review"],["TDS return","Anil Menon","Due in 7 days"]]}/>,Invoices:<Rows rows={[["INV-2026-104","₹45,000","Sent"],["INV-2026-101","₹28,500","Paid"],["INV-2026-092","₹18,000","Overdue"]]}/>,Documents:<Rows rows={[["GST purchase register","Received","Verified"],["Bank statement · July","Requested","Reminder sent"],["TDS certificates","Missing","Due today"]]}/>,Activity:<Rows rows={[["GST return task assigned","Priya Shetty","2h ago"],["Bank statement received","Client portal","Yesterday"],["Invoice INV-2026-104 sent","Artha","12 Aug"]]}/>};return <AppWindow><div className="p-4 md:p-5"><div className="mb-5 flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--mkt-wash-hi)] text-[12px] font-semibold text-mkt-primary">VS</span><div><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">V Srinivasulu and Co</p><p className="mt-1 text-[11px] text-mkt-fg-muted">Active client · Hyderabad</p></div><span className="ml-auto"><Tag tone="accent">Active</Tag></span></div><div role="tablist" aria-label="Client record sections" className="mb-4 flex gap-1 overflow-x-auto border-b border-mkt-border">{tabs.map(item=><button key={item} type="button" role="tab" aria-selected={tab===item} onClick={()=>setTab(item)} className={cn("min-h-11 border-b-2 px-3 text-[11px] whitespace-nowrap",tab===item?"border-mkt-primary text-mkt-primary":"border-transparent text-mkt-fg-muted hover:text-mkt-fg")}>{item}</button>)}</div><div key={tab} className="mkt-fade-up">{content[tab]}</div></div></AppWindow>}

function Work(){const [selected,setSelected]=useState("GSTR-3B · Meridian Textiles");const columns: [string, string[]][]=[["To do",["GSTR-3B · Meridian Textiles","ITR filing · Alpha Pvt Ltd"]],["In progress",["Audit working papers","Client documents · Kavya"]],["Review",["GST mismatch · Kavya Exports"]],["Done",["TDS return · Sunrise Traders"]]];return <AppWindow><div className="p-4 md:p-5"><div className="mb-5"><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">Know what needs to happen — and who owns it.</p><p className="mt-1 text-[11px] text-mkt-fg-muted">Work is visible by owner, priority and due date.</p></div><div className="overflow-x-auto"><div className="grid min-w-[650px] grid-cols-4 gap-2.5">{columns.map(([title,tasks])=><div key={title} className="rounded-xl border border-mkt-border bg-mkt-surface-2 p-2.5"><div className="mb-3 flex justify-between text-[9.5px] tracking-[.09em] text-mkt-fg-muted uppercase"><span>{title}</span><span>{tasks.length}</span></div>{tasks.map((task,i)=><button key={task} type="button" onClick={()=>setSelected(task)} className={cn("mb-2 w-full rounded-lg border p-2.5 text-left transition-colors last:mb-0",selected===task?"border-mkt-primary bg-[var(--mkt-wash)]":"border-mkt-border bg-mkt-surface hover:border-mkt-border-hi")}><span className="block text-[10.5px] leading-snug text-mkt-fg">{task}</span><span className="mt-2 flex justify-between text-[9px] text-mkt-fg-muted"><span>{i%2?"Priya Shetty":"Ravi Kumar"}</span><span>{i===0?"Due 20 Aug":"Medium"}</span></span></button>)}</div>)}</div></div><div aria-live="polite" className="mt-4 rounded-xl border border-mkt-primary/40 bg-[var(--mkt-wash)] px-3.5 py-3 text-[11px] text-mkt-fg"><span className="font-medium text-mkt-primary">Selected task</span><span className="mx-2 text-mkt-fg-muted">·</span>{selected}<span className="mx-2 text-mkt-fg-muted">·</span>Owner and due date ready for review.</div></div></AppWindow>}

function Documents(){const [received,setReceived]=useState<Record<string,boolean>>({"GST Purchase Register":true,"Bank Statement":false,"TDS Certificates":false,"Audit Documents":true});return <AppWindow><div className="p-4 md:p-5"><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">Stop chasing documents across WhatsApp and email.</p><div className="mt-1 flex justify-between text-[11px] text-mkt-fg-muted"><span>Kavya Exports · July filing</span><span>{Object.values(received).filter(Boolean).length}/4 received</span></div><div className="mt-5 space-y-2">{Object.entries(received).map(([name,done])=><button key={name} type="button" onClick={()=>setReceived(items=>({...items,[name]:!items[name]}))} className="flex min-h-12 w-full items-center gap-3 rounded-xl border border-mkt-border bg-mkt-surface-2 px-3 text-left hover:border-mkt-border-hi"><span className={cn("grid size-4 place-items-center rounded border",done?"border-mkt-primary bg-mkt-primary text-mkt-primary-fg":"border-mkt-border-hi")}><Check className={cn("size-3",!done&&"invisible")}/></span><span className="flex-1 text-[12px] text-mkt-fg">{name}</span><Tag tone={done?"accent":"medium"}>{done?"Received":"Requested"}</Tag></button>)}</div><Progress/></div></AppWindow>}
function Progress(){return <div className="mt-6 grid grid-cols-4 gap-2 border-t border-mkt-border pt-5">{["Requested","Reminder","Received","Verified"].map((stage,i)=><div key={stage} className="text-center"><span className={cn("mx-auto mb-2 grid size-7 place-items-center rounded-full border text-[10px]",i<2?"border-mkt-primary bg-mkt-primary text-mkt-primary-fg":"border-mkt-border text-mkt-fg-muted")}>{i+1}</span><span className="text-[9px] text-mkt-fg-muted">{stage}</span></div>)}</div>}

function Billing(){return <AppWindow><div className="p-4 md:p-5"><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">See what is billed, outstanding and overdue.</p><div className="mt-5 grid grid-cols-2 gap-2.5 lg:grid-cols-4"><Metric label="Revenue" value="₹1.21Cr" sub="This month"/><Metric label="Outstanding" value="₹4.2L" sub="16 clients"/><Metric label="Overdue" value="₹54K" sub="3 invoices" tone="high"/><Metric label="Paid" value="₹8.4L" sub="This month"/></div><div className="mt-5"><Rows rows={[["INV-2026-104 · Kavya Exports","₹45,000","Sent"],["INV-2026-101 · Meridian Textiles","₹28,500","Paid"],["INV-2026-092 · Alpha Pvt Ltd","₹18,000","Overdue"],["INV-2026-087 · Sri Balaji Traders","₹22,000","Draft"]]}/></div></div></AppWindow>}

function Reconciliation(){const [created,setCreated]=useState(false);const stages=created?["Exception","Task created","Assigned","Resolved"]:["Exception","Awaiting review","Assigned","Resolved"];return <AppWindow><div className="p-4 md:p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">Find exceptions before they become problems.</p><p className="mt-1 text-[11px] text-mkt-fg-muted">GSTR-2B vs purchase register · Kavya Exports</p></div><Tag tone="high">High risk</Tag></div><div className="mt-5 grid grid-cols-2 gap-3"><div className={card}><p className="text-[9px] tracking-[.08em] text-mkt-fg-muted uppercase">Matched</p><p className="mkt-num mt-2 font-mkt-display text-[32px] font-semibold text-mkt-primary">94%</p></div><div className={card}><p className="text-[9px] tracking-[.08em] text-mkt-fg-muted uppercase">Exceptions</p><p className="mkt-num mt-2 font-mkt-display text-[32px] font-semibold text-mkt-destructive">6%</p></div></div><div className="mt-4 rounded-xl border border-mkt-destructive/40 bg-[var(--mkt-danger-wash)] p-4"><div className="flex items-center gap-2"><TriangleAlert className="size-4 text-mkt-destructive"/><p className="text-[12px] font-medium text-mkt-fg">GSTIN mismatch</p></div><div className="mt-3 grid grid-cols-2 gap-3 text-[10.5px]"><span className="text-mkt-fg-muted">Client <b className="ml-1 font-medium text-mkt-fg">Kavya Exports</b></span><span className="text-mkt-fg-muted">Amount <b className="mkt-num ml-1 font-medium text-mkt-fg">₹1,24,500</b></span></div></div><button type="button" onClick={()=>setCreated(true)} disabled={created} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-mkt-brand-mid px-4 text-[12px] font-semibold text-mkt-on-brand disabled:opacity-70">{created?<><CircleCheckBig className="size-4"/>Task created</>:<>Create task<ChevronRight className="size-4"/></>}</button><div aria-live="polite" className="mt-5 grid grid-cols-4 gap-1.5 border-t border-mkt-border pt-5">{stages.map((stage,i)=><div key={stage} className="text-center"><span className={cn("mx-auto mb-2 grid size-7 place-items-center rounded-full border text-[10px]",i===0||created?"border-mkt-primary bg-[var(--mkt-wash-hi)] text-mkt-primary":"border-mkt-border text-mkt-fg-muted")}>{i+1}</span><span className="block text-[9px] leading-tight text-mkt-fg-muted">{stage}</span></div>)}</div></div></AppWindow>}

function Compliance(){return <AppWindow><div className="p-4 md:p-5"><p className="font-mkt-display text-[18px] font-semibold text-mkt-fg">Your compliance command center.</p><p className="mt-1 text-[11px] text-mkt-fg-muted">The partner sees what is due before it becomes overdue.</p><div className="mt-5 overflow-hidden rounded-xl border border-mkt-border">{[["GST Return","Due in 3 days","medium"],["TDS Return","Due in 7 days","accent"],["ITR Filing","Due in 12 days","accent"],["DSC","Expires in 24 days","high"]].map(([name,due,tone])=><div key={name} className="flex items-center gap-3 border-b border-mkt-border bg-mkt-surface-2 px-3.5 py-4 last:border-0"><FileText className="size-4 text-mkt-primary"/><span className="flex-1 text-[12px] text-mkt-fg">{name}</span><Tag tone={tone as "accent"|"medium"|"high"}>{due}</Tag></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2.5"><Metric label="Due soon" value="9" sub="Next 7 days" tone="medium"/><Metric label="Overdue" value="2" sub="Needs review" tone="high"/><Metric label="Completed" value="34" sub="This month"/></div></div></AppWindow>}

function Experience({active}:{active:Module}){return <div key={active} className="mkt-fade-up" role="tabpanel" id={`explorer-panel-${active}`} aria-labelledby={`explorer-tab-${active}`} tabIndex={0}>{active==="overview"&&<Overview/>}{active==="clients"&&<Clients/>}{active==="work"&&<Work/>}{active==="documents"&&<Documents/>}{active==="billing"&&<Billing/>}{active==="reconciliation"&&<Reconciliation/>}{active==="compliance"&&<Compliance/>}</div>}

export function ProductExplorer(){const [active,setActive]=useState<Module>("overview");const onKeyDown=(e:React.KeyboardEvent<HTMLButtonElement>,index:number)=>{const keys=["ArrowRight","ArrowDown","ArrowLeft","ArrowUp","Home","End"];if(!keys.includes(e.key))return;e.preventDefault();const next=e.key==="Home"?0:e.key==="End"?MODULES.length-1:(index+(e.key==="ArrowRight"||e.key==="ArrowDown"?1:MODULES.length-1))%MODULES.length;const key=MODULES[next]![0];setActive(key);document.getElementById(`explorer-tab-${key}`)?.focus()};const description=MODULES.find(([key])=>key===active)?.[3];return <Section id="explore"><div className="mx-auto max-w-3xl text-center"><Eyebrow>Explore Artha</Eyebrow><h2 className="font-mkt-display text-[clamp(2rem,4vw,3rem)] font-semibold tracking-[-.035em] text-mkt-fg">See how your firm&apos;s work connects.</h2><p className="mt-3 text-[15px] text-mkt-fg-muted">Explore the workflows inside Artha — without leaving the page.</p></div><div className="mt-10 overflow-hidden rounded-2xl border border-mkt-border bg-mkt-surface p-2 shadow-[var(--mkt-shadow-elegant)] md:p-3"><div className="grid gap-3 lg:grid-cols-[188px_minmax(0,1fr)]"><div role="tablist" aria-label="Explore Artha modules" aria-orientation="vertical" className="mkt-edge-fade flex gap-1 overflow-x-auto px-1 pb-1 lg:block lg:overflow-visible lg:px-0 lg:pb-0">{MODULES.map(([key,label,Icon],index)=><button key={key} id={`explorer-tab-${key}`} type="button" role="tab" aria-selected={active===key} aria-controls={`explorer-panel-${key}`} tabIndex={active===key?0:-1} onClick={()=>setActive(key)} onKeyDown={e=>onKeyDown(e,index)} className={cn("flex min-h-11 shrink-0 items-center gap-2.5 rounded-lg px-3 text-left text-[12px] transition-colors lg:mb-1 lg:w-full",active===key?"bg-[var(--mkt-wash-hi)] font-semibold text-mkt-primary":"text-mkt-fg-muted hover:bg-mkt-surface-2 hover:text-mkt-fg")}><Icon className="size-4"/>{label}<span className={cn("ml-auto h-px w-5 bg-mkt-primary transition-opacity",active===key?"opacity-100":"opacity-0")}/></button>)}</div><div className="min-w-0"><Experience active={active}/><p className="mt-3 px-1 text-[11px] text-mkt-fg-muted"><span className="mr-2 text-mkt-primary">Connected workflow</span>{description}</p></div></div></div></Section>}
